### ISSUE TITLE
Running Project

### ISSUE THREAD

**Issue by idkjs** [curtiswilkinson/reason-roomservice#1]
How do you run this project? Compiles running the js files doesnt output anything.

Thanks

**Comment by curtiswilkinson** [comment]
This is my very, very early attempt of porting https://github.com/curtiswilkinson/roomservice across from typescript to ReasonML

It won't do much of anything at this stage,  pretty much all it does is read in configuration files based on CLI flags (for example `node ./src/main.bs.js --project ./mock/roomservice.config.yml`

**Comment by idkjs** [comment]
Keep up the good work, brother.
